function precleantest = import_preclean(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as a matrix.
%   PRECLEANED2315 = IMPORTFILE(FILENAME) Reads data from text file
%   FILENAME for the default selection.
%
%   PRECLEANED2315 = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from
%   rows STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   precleaned2315 = importfile('1005 pre-cleaned 2-3-15.csv', 2, 8027);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2015/11/04 15:40:54

%% Initialize variables.
delimiter = ',';
if nargin<=2
    startRow = 2;
    endRow = inf;
end

%% Format string for each line of text:
%   column1: text (%s)
%	column2: double (%f)
%   column3: text (%s)
%	column4: text (%s)
%   column5: text (%s)
%	column6: double (%f)
%   column7: text (%s)
%	column8: double (%f)
%   column10: datetimes (%{HH:mm:ss}D)
%	column11: double (%f)
%   column12: double (%f)
%	column13: double (%f)
%   column14: text (%s)
%	column15: text (%s)
%   column16: text (%s)
%	column17: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%s%f%s%s%s%f%s%f%*s%{HH:mm:ss}D%f%f%f%s%s%s%f%*s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
precleantest = table(dataArray{1:end-1}, 'VariableNames', {'Time__HH_mm_ss_','Skin_Temperature__IR_Thermometer','Body_Position','Ambulation_Status','Low_HR_Confidence','HR_Confidence','Low_BR_Confidence','BR_Confidence','time','Lateral_Acc','Longitudinal_Acc','Vertical_Acc','date','HR','BR','activity'});

% For code requiring serial dates (datenum) instead of datetime, uncomment
% the following line(s) below to return the imported dates as datenum(s).

% precleaned2315.time=datenum(precleaned2315.time);

