function [DateMdyyyy,TimeHHmmss,LateralAcc,LongitudinalAcc,VerticalAcc] = import_acc(directory)
%IMPORTFILE Import numeric data from a text file as column vectors.
%   [DATEMDYYYY,TIMEHHMMSS1,LATERALACC1,LONGITUDINALACC1,VERTICALACC1] =
%   IMPORTFILE(FILENAME) Reads data from text file FILENAME for the default
%   selection.
%
%   [DATEMDYYYY,TIMEHHMMSS1,LATERALACC1,LONGITUDINALACC1,VERTICALACC1] =
%   IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from rows STARTROW
%   through ENDROW of text file FILENAME.
%
% Example:
%   [DateMdyyyy,TimeHHmmss1,LateralAcc1,LongitudinalAcc1,VerticalAcc1] = importfile('AccMG1005 12-12-14a.csv',2, 4213);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2015/09/29 14:08:10

%% Initialize variables.
%delimiter = ',';
%if nargin<=2
%    startRow = 2;
%    endRow = inf;
%end

%% Format string for each line of text:
%   column1: datetimes (%{MM/dd/yyyy}D)
%	column2: text (%s)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
% For more information, see the TEXTSCAN documentation.
%formatSpec = '%{MM/dd/yyyy}D%s%f%f%f%[^\n\r]';

%% Open the text file.
%fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
%dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
%for block=2:length(startRow)
%    frewind(fileID);
%    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
%    for col=1:length(dataArray)
%        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
%    end
%end

%% Close the text file.
%fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.


%filename='AccMG1005 12-12-14a';
%%%%%read csv file from other routine

dataArray=readtable(directory);


%% Allocate imported array to column variable names
DateMdyyyy = dataArray{:, 1};
TimeHHmmss = dataArray{:, 2};
LateralAcc = dataArray{:, 3};
LongitudinalAcc = dataArray{:, 4};
VerticalAcc = dataArray{:, 5};

% For code requiring serial dates (datenum) instead of datetime, uncomment
% the following line(s) below to return the imported dates as datenum(s).

% DateMdyyyy=datenum(DateMdyyyy);


